### ISSUE TITLE
Setup Tailwind/purgecss/postcss

### ISSUE THREAD

**Issue by mattmcmanus** [schoolsOut/schoolsOut#2]
https://github.com/chrism/emberjs-tailwind-purgecss

This feels like a solid place to start for a new project to me. You may have strong opinions about functional CSS. I just thought I'd throw it out there for now

**Comment by mminkoff** [comment]
So, tailwind and not bulma?  Admittedly I haven't used a functional CSS framework, but that's because I can't stand the idea...

**Comment by mattmcmanus** [comment]
Potentially helpful reading: https://mcmanus.io/2018/i-dont-want-to-but-im-giving-functional-CSS-a-try

**Comment by mattmcmanus** [comment]
I'm happy to do whatever, but that blog post documents my change in heart.

**Comment by mminkoff** [comment]
I guess I'm willing to give it a try.  I think there are two things that potentially mitigate where you were in that article:

1. FlexBox - I do pretty much no extra nonsense to make my css work these days.
2. CSS Modules.  I may not be totally clear (in my thinking) about how Tailwind would fit with CSS Modules.  Maybe it's a perfect match, with modules solving the semantic issues?

**Comment by mattmcmanus** [comment]
@mminkoff If you're hesitant, i'm totally down for doing CSS Modules. 

As a point of reference, here is how flexbox stuff would be handled with tailwind: https://tailwindcss.com/docs/display/#flex

**Comment by mminkoff** [comment]
I'm good with doing both.
